databases:
  - name: association-accessors
    databaseName: association-accessors
    user: association-accessors
    region: ohio
    plan: starter

services:
  - type: web
    name: association-accessors
    region: ohio
    plan: starter
    runtime: ruby
    healthCheckPath: /up
    buildCommand: "./bin/render-build.sh"
    preDeployCommand: "./bin/rails db:migrate"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: envoy
          property: connectionString
      - key: WEB_CONCURRENCY
        value: 2
